name: splitwise
description: A Splitwise clone app built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/expense_illustration.png
